identifier: l78e39pe88qb51v8
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: blog
homeFolder: /Users/nelsongutierrez/Documents/Personal Projects/blog/blog
distFolder: ./dist/blog
outDir: /Users/nelsongutierrez/Documents/Personal Projects/blog/blog/dist/static
handle404: ''
allowErrorCollect: false
